title: Creación blog con Jekyll
author: E539238
email: roberto.rodriguez@sivsa.com
description: > # this means to ignore newlines until "baseurl:"
  Curso para crear blogs con Jekyll

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-time-machine
